### ISSUE TITLE
Add additional sensors

### ISSUE THREAD

**Issue by Misiu** [Makerfabs/Home-Assistant-Relay-8-Channel#1]
Hi there,
I was searching for a relay board that I can use with ESPHome and I found your board.
It looks great, but I have one additional question:
Do you allow/support additional sensors?
In my case I want to connect 5 DS18B20 sensors and one move sensor (simple input), so ideally I'd like to use your board to read the temperature and control the relays even when Home Assistant is unavailable.

**Comment by poelzi** [comment]
I have a similar use case. For me, haveing some free pins that are currently NC on a pin header would be enough. I will just bodge my self up ;)

**Comment by Misiu** [comment]
@195cn can we get any info on this issue? Thank you :)

**Comment by 195cn** [comment]
There is no additional GPIO for secondary development at the moment, I suggest sending an email directly to techsupport@makerfabs.com, so that my boss can see it and consider new products.    : )
